### ISSUE TITLE
seg fault on ubuntu12.04

### ISSUE THREAD

**Issue by fdeheeger** [ppham27/sas_to_csv#1]
Hi,

good idea to write the sasdb converter in c, either for performance or to suppress R dependency in that job.

I try to use it on ubuntu 12.04 64 bits.. I just compile it : $make, and my first test on a test db leads me to a 'seg fault'.
do you advise any gcc version, system or anything else ?

thanks for any answer.
## 

François Deheeger

**Comment by ppham27** [comment]
Hi Francois,

Sorry that it isn't working for you. I'll do my best to help. I don't have a Ubuntu test system, unfortunately. 

I've tried so far on an Macbook Pro OS X 10.6 and a Macbook Air OS X 10.7. It works fine on most of the files in test_files dir. Have you tried it on any of those? On my Macbook Air, it does segfault or produce another error on a few of them (br, cfrance, cola, cola2, coutline, crime, elemapi, elemapi2, gfrance2, goutline, lon1, lon2, london, mroz, nations, nels, nels_small, olympics, physeds2006, star, stockton2, tunafish, tunafish_small, xfrance, xfrance2, xoutline, and yrbscol don't work).

If you can provide me with your test db that would help. If that's not possible,  at the very least do you happen to know the SAS version or OS of the SAS host that it came from?

I wasn't aware people were actually using the converter, so I never got around to addressing the problem files. I'll work on making the converter more robust over the next two days.

-Phil

**Comment by fdeheeger** [comment]
Hi,

thanks for answering !

2012/10/16 ppham27 notifications@github.com

> Hi Francois,
> 
> Sorry that it isn't working for you. I'll do my best to help. I don't have
> a Ubuntu test system, unfortunately.
> 
> I've tried so far on an Macbook Pro OS X 10.6 and a Macbook Air OS X 10.7.
> It works fine on most of the files in test_files dir. Have you tried it on
> any of those. On my Macbook Air, it does segfault or produce another error
> on a few of them (br, cfrance, cola, cola2, coutline, crime, elemapi,
> elemapi2, gfrance2, goutline, lon1, lon2, london, mroz, nations, nels,
> nels_small, olympics, physeds2006, star, stockton2, tunafish,
> tunafish_small, xfrance, xfrance2, xoutline, and yrbscol don't work).
> 
> If you can provide me with your test db that would help. If that's not
> possible, at the very least do you happen to know the SAS version or OS of
> the SAS host that it came from?
> 
> The test file i used this morning was 'beer.sas7bdat', coming from your
> test db (do not know why i choose that one..).
> 
> I wasn't aware people were actually using the converter, so I never got
> around to addressing the problem files. I'll work on making the converter
> more robust over the next two days.
> 
> I wasn't aware of this converter... Actually, i have already used the one
> from which you have started.
> Sometimes i work with people who get db extracts coming from sas. They do
> not always take the time to convert it in something more flexible like a
> csv, or an excel file. I was happy to find the R converter (i do not have
> access to a sas machine) but i am more a pythonista, and the dependency to
> R is not really easy to maintain in a environment where people may use
> linux or windows.

by chance, i found your project and so i give it a try...
do not waste too much time if you do not need it, but if you want to make
it more efficient i can give you feedback of it on linux and windows.

## 

François Deheeger

**Comment by fdeheeger** [comment]
Here is the first feedback.

I try to compile it on my home computer (ubuntu 12.04 - 32 bits) and it works !
The only difference that i see from office and home computer is the
architecture : 64 vs 32 bits.

So it seems that the 32 or 64 question impacts the response of the code.

The behaviour is the same as you, some conversion failed -- see test.log

## Regards

François

2012/10/16 François Deheeger francois.deheeger@free.fr:

> Hi,
> 
> thanks for answering !
> 
> 2012/10/16 ppham27 notifications@github.com
> 
> > Hi Francois,
> > 
> > Sorry that it isn't working for you. I'll do my best to help. I don't have
> > a Ubuntu test system, unfortunately.
> > 
> > I've tried so far on an Macbook Pro OS X 10.6 and a Macbook Air OS X 10.7.
> > It works fine on most of the files in test_files dir. Have you tried it on
> > any of those. On my Macbook Air, it does segfault or produce another error
> > on a few of them (br, cfrance, cola, cola2, coutline, crime, elemapi,
> > elemapi2, gfrance2, goutline, lon1, lon2, london, mroz, nations, nels,
> > nels_small, olympics, physeds2006, star, stockton2, tunafish,
> > tunafish_small, xfrance, xfrance2, xoutline, and yrbscol don't work).
> > 
> > If you can provide me with your test db that would help. If that's not
> > possible, at the very least do you happen to know the SAS version or OS of
> > the SAS host that it came from?
> 
> The test file i used this morning was 'beer.sas7bdat', coming from your test
> db (do not know why i choose that one..).
> 
> > I wasn't aware people were actually using the converter, so I never got
> > around to addressing the problem files. I'll work on making the converter
> > more robust over the next two days.
> 
> I wasn't aware of this converter... Actually, i have already used the one
> from which you have started.
> Sometimes i work with people who get db extracts coming from sas. They do
> not always take the time to convert it in something more flexible like a
> csv, or an excel file. I was happy to find the R converter (i do not have
> access to a sas machine) but i am more a pythonista, and the dependency to R
> is not really easy to maintain in a environment where people may use linux
> or windows.
> 
> by chance, i found your project and so i give it a try...
> do not waste too much time if you do not need it, but if you want to make it
> more efficient i can give you feedback of it on linux and windows.
> 
> ## 
> 
> François Deheeger

## 

François Deheeger

**Comment by fdeheeger** [comment]
Second part of my evening test.
let's go back to a 64 bits ubuntu machine.
i modify the makefile adding the option -m32 to gcc. That option
forces the use of 32bits libraries. and... it works.

the C code seems to be 32 bits specific.

## 

François Deheeger

**Comment by ppham27** [comment]
Thanks a lot for your help. I added the -m32 flag to the makefile, and I also fixed how it was parsing numeric data. It should now run on all the sas7bdat files in the test_file folder now except for those that were produced by Linux and SunOS. I'm not quite sure how to parse those files, yet.
